solutions for module 3 tasks 1, 2, 3
js-tasks-ru/jsbasic-20210906-2_dmitriy019 pull request #4
Opened 2021-09-20 20:00 UTC by dgogin

2021-09-20 20:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-20 20:17 UTC, SinimaWath requested changes

2021-09-20 20:17 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names;
Давай напишим использую map

2021-09-20 20:17 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  let filtered = Object.assign(arr).filter(item => ((item >= a) && (item <= b)));
А зачем тут Object.assign(arr). Кажется это лишнее

2021-09-20 20:17 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  }
Давай это заменим на map

2021-09-22 12:31 UTC, dgogin commented on 3-module/3-task/index.js
> +  }
Заменил

2021-09-22 12:31 UTC, dgogin commented on 3-module/2-task/index.js
> +  let filtered = Object.assign(arr).filter(item => ((item >= a) && (item <= b)));
Да, лишнее. filter массив не меняет.

2021-09-22 16:38 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-23 12:13 UTC, SinimaWath requested changes

2021-09-23 12:13 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  }).join("");
Сейчас в map - у тебя слишком много логики.

Давай разделим фильтрацию в filter. 
Преобразование в map
А добавление '\n' в join -> join('\n')

2021-09-24 13:24 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-25 15:51 UTC, SinimaWath approved these changes

2021-09-25 15:52 UTC, merged