module 4: all 3 task solved
js-tasks-ru/jsbasic-20210906-2_dmitriy019 pull request #5
Opened 2021-09-26 20:42 UTC by dgogin

2021-09-26 20:43 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-27 18:57 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-27 18:59 UTC, dgogin commented on 4-module/3-task/index.js
> +        if (tr.cells[1].innerHTML < 18) tr.setAttribute("style", "text-decoration: line-through");
исправил. Спасибо!

2021-09-27 18:59 UTC, dgogin commented on 4-module/1-task/index.js
> +    li.appendChild(textnode);
исправил

2021-09-27 18:59 UTC, dgogin commented on 4-module/1-task/index.js
> +  var ul = document.createElement('ul');
Сорри, привычка сработала...

2021-09-28 10:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-28 12:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-29 11:44 UTC, SinimaWath requested changes

2021-09-29 11:44 UTC, SinimaWath commented on 5-module/1-task/index.js
> +  let btn = (document.getElementsByClassName("hide-self-button"))[0];
Давай все таки, используем querySelector. Он тут как раз будет подходить больше:
```
let btn = document.querySelector('.hide-self-button');
```

2021-09-29 11:44 UTC, SinimaWath commented on 5-module/2-task/index.js
> +  let btn = (document.getElementsByClassName("toggle-text-button"))[0];
Тут querySelector - будет проще, давай его используем

2021-09-30 12:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-10-01 23:02 UTC, SinimaWath approved these changes
Все круто! Молодец!

2021-10-01 23:03 UTC, merged